---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: ceph-objectstore-s3
  namespace: rook-ceph
  annotations:
    external-dns.alpha.kubernetes.io/is-public: "true"
spec:
  parentRefs:
    - name: external-gateway
      namespace: network
      sectionName: https-56kbps
    - name: internal-gateway
      namespace: network
      sectionName: https-56kbps
  hostnames:
    - "s3.56kbps.io"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: rook-ceph-rgw-ceph-objectstore
          port: 80
