---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: enigma-bbs-outpost-edit
  namespace: default
spec:
  ingressClassName: internal
  rules:
    - host: edit.halfduplex.io
      http:
        paths:
          - backend:
              service:
                name: ak-outpost-halfduplex
                port:
                  number: 9000
            path: /outpost.goauthentik.io
            pathType: Prefix
  tls:
    - hosts:
        - edit.halfduplex.io
      secretName: halfduplex-io-production-tls
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: enigma-bbs-outpost-draw
  namespace: default
spec:
  ingressClassName: internal
  rules:
    - host: draw.halfduplex.io
      http:
        paths:
          - backend:
              service:
                name: ak-outpost-halfduplex
                port:
                  number: 9000
            path: /outpost.goauthentik.io
            pathType: Prefix
  tls:
    - hosts:
        - draw.halfduplex.io
      secretName: halfduplex-io-production-tls
---
apiVersion: v1
kind: Service
metadata:
  name: ak-outpost-halfduplex
  namespace: default
spec:
  type: ExternalName
  externalName: ak-outpost-halfduplex.security.svc.cluster.local
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
