---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
components:
  - ../../components/common
resources:
  - ./gatus/ks.yaml
  #- ./grafana/ks.yaml
  - ./kromgo/ks.yaml
  #- ./kube-prometheus-stack/ks.yaml
  #- ./loki/ks.yaml
  #- ./prometheus-operator-crds/ks.yaml
  #- ./promtail/ks.yaml
  #- ./unpoller/ks.yaml
  #- ./exporters
