---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cluster-secrets
  namespace: flux-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: cluster-secrets
    template:
      engineVersion: v2
      type: Opaque
      data:
        # Network settings
        SECRET_DOMAIN: '{{ .SECRET_DOMAIN }}'
        SECRET_INTERNAL_DOMAIN: '{{ .SECRET_INTERNAL_DOMAIN }}'
        SECRET_INTERNAL_DOMAIN_ESCAPE: '{{ .SECRET_INTERNAL_DOMAIN_ESCAPE }}'
        CILIUM_LB_RANGE_START: '{{ .CILIUM_LB_RANGE_START }}'
        CILIUM_LB_RANGE_END: '{{ .CILIUM_LB_RANGE_END }}'
        SECRET_CILIUM_INTERNAL_VIP: '{{ .SECRET_CILIUM_INTERNAL_VIP }}'
        SECRET_CILIUM_EXTERNAL_VIP: '{{ .SECRET_CILIUM_EXTERNAL_VIP }}'
        SECRET_NGINX_INTERNAL_VIP: '{{ .SECRET_NGINX_INTERNAL_VIP }}'
        SECRET_NGINX_EXTERNAL_VIP: '{{ .SECRET_NGINX_EXTERNAL_VIP }}'
        SECRET_VIP_PLEX: '{{ .SECRET_VIP_PLEX }}'
        SECRET_VIP_SMTP: '{{ .SECRET_VIP_SMTP }}'
        SECRET_VIP_ZIGBEE: '{{ .SECRET_VIP_ZIGBEE }}'
        SECRET_VIP_EMQX: '{{ .SECRET_VIP_EMQX }}'
        SECRET_NAS_DOOM: '{{ .SECRET_NAS_DOOM }}'
        SECRET_NAS_MORDOR: '{{ .SECRET_NAS_MORDOR }}'
        SECRET_NFS_SERVER: '{{ .SECRET_NFS_SERVER }}'
        SECRET_NFS_PATH: '{{ .SECRET_NFS_PATH }}'
        SECRET_NFS_PATH_CONFIG: '{{ .SECRET_NFS_PATH_CONFIG }}'
        SECRET_NFS_PATH_DATA: '{{ .SECRET_NFS_PATH_DATA }}'
        SECRET_NFS_PATH_MEDIA: '{{ .SECRET_NFS_PATH_MEDIA }}'
        SECRET_METAL_GATEWAY: '{{ .SECRET_METAL_GATEWAY }}'
        SECRET_METAL_CIDR: '{{ .SECRET_METAL_CIDR }}'
        SECRET_CIDR: '{{ .SECRET_CIDR }}'
        SECRET_ACME_EMAIL: '{{ .SECRET_ACME_EMAIL }}'
        SECRET_CLOUDFLARE_TUNNEL_ID: '{{ .SECRET_CLOUDFLARE_TUNNEL_ID }}'
        SECRET_CLOUDFLARE_ACCOUNT_ID: '{{ .SECRET_CLOUDFLARE_ACCOUNT_ID }}'
  dataFrom:
    - extract:
        key: cluster-secrets
