---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: dozzle
spec:
  interval: 12h
  provider: generic
  url: oci://ghcr.io/bjw-s-labs/charts/app-template
  ref:
    tag: 4.2.0
